In [1]:
import pandas as pd
import numpy as np
import matplotlib . pyplot as plt

In [4]:
#1.2
df = pd.read_excel(r'C:/Users/Federico/Desktop/UdeSA/Maestría/Big Data/TP3/usu_hogar_T121.xlsx')
print (df)

                              CODUSU  ANO4  TRIMESTRE  NRO_HOGAR  REALIZADA  \
0      TQRMNOQUPHMKKUCDEOJAH00701956  2021          1          1          1
1      TQRMNOPWXHMOKRCDEGLDF00701361  2021          1          1          1
2      TQRMNOSUXHMMLPCDEGPDJ00701412  2021          1          1          1
3      TQRMNORRQHKMKPCDEFOCD00653036  2021          1          1          1
4      TQRMNOPYYHMKKRCDEHIBB00699594  2021          1          1          1
...                              ...   ...        ...        ...        ...
15418  TQRMNOSRSHJLKNCDEHNHB00686513  2021          1         72          1
15419  TQRMNOPUPHMOKRCDEHNHB00698996  2021          1         51          1
15420  TQRMNOPPTHKKKRCDEHPJB00655306  2021          1         71          1
15421  TQRMNOSTVHLKSQCDEIJAH00651298  2021          1         51          1
15422  TQRMNOPVYHKMLQCDEGGFB00653370  2021          1         51          1

       REGION MAS_500  AGLOMERADO  PONDERA  IV1  ...  GDECCFR  PDECCFR  \
0          44       N          93       77    1  ...      NaN     12.0
1          41       N          15      140    1  ...      NaN      6.0
2          40       N          19      177    1  ...      NaN      7.0
3          41       N           8      136    1  ...      NaN      2.0
4          40       N          22      175    1  ...      NaN      7.0
...       ...     ...         ...      ...  ...  ...      ...      ...
15418      42       N          27      496    1  ...      9.0      NaN
15419      42       N          27      238    1  ...      8.0      NaN
15420      40       S          29      527    1  ...      7.0      NaN
15421       1       S          33     1673    1  ...      8.0      NaN
15422      42       S          10      431    1  ...     12.0      NaN

       ADECCFR  PONDIH  VII1_1  VII1_2  VII2_1  VII2_2  VII2_3  VII2_4
0         12.0       0      96       0      98       0       0       0
1          8.0     191       2       0       3       5       6       0
2          8.0     177       3       0       4       6       0       0
3          3.0     132       2       0       3       0       0       0
4          8.0     205       1       2       3       0       0       0
...        ...     ...     ...     ...     ...     ...     ...     ...
15418     10.0     497       1       0      98       0       0       0
15419      9.0     240      97       0      98       0       0       0
15420      8.0     664       1       0      98       0       0       0
15421      8.0    2016       1       0      98       0       0       0
15422     12.0       0       1       0      98       0       0       0

[15423 rows x 88 columns]

In [5]:
#1.2 continuación
df.drop(df[df['AGLOMERADO'] < 32.0].index, inplace=True)
df.drop(df[df['AGLOMERADO'] > 33.0].index, inplace=True)
print(df)

                              CODUSU  ANO4  TRIMESTRE  NRO_HOGAR  REALIZADA  \
15     TQRMNOQXUHJMMUCDEIJAH00693031  2021          1          1          1
21     TQRMNOSRPHLLNRCDEIJAH00651171  2021          1          1          1
24     TQRMNOPVUHKLMNCDEIIAD00655817  2021          1          1          1
36     TQRMNORYTHLOPMCDEIJAH00655933  2021          1          1          1
43     TQRMNOQPVHLMNNCDEIIAD00650542  2021          1          1          1
...                              ...   ...        ...        ...        ...
15373  TQRMNOQYSHMOLTCDEIJAH00700276  2021          1          1          1
15382  TQRMNOURVHMNONCDEIIAD00700616  2021          1          1          1
15391  TQRMNORRWHJMOPCDEIIAD00690119  2021          1          1          1
15412  TQRMNOQWRHLOMPCDEIJAH00650932  2021          1          1          1
15421  TQRMNOSTVHLKSQCDEIJAH00651298  2021          1         51          1

       REGION MAS_500  AGLOMERADO  PONDERA  IV1  ...  GDECCFR  PDECCFR  \
15          1       S          33     3255    1  ...      3.0      NaN
21          1       S          33     2331    1  ...      4.0      NaN
24          1       S          32     3219    1  ...      6.0      NaN
36          1       S          33    11578    1  ...      2.0      NaN
43          1       S          32     4300    1  ...     12.0      NaN
...       ...     ...         ...      ...  ...  ...      ...      ...
15373       1       S          33     7809    1  ...      1.0      NaN
15382       1       S          32     3772    2  ...      9.0      NaN
15391       1       S          32     1379    2  ...     10.0      NaN
15412       1       S          33     8638    1  ...      1.0      NaN
15421       1       S          33     1673    1  ...      8.0      NaN

       ADECCFR  PONDIH  VII1_1  VII1_2  VII2_1  VII2_2  VII2_3  VII2_4
15         4.0    5286       2       0      98       0       0       0
21         5.0    3953       2       0      98       0       0       0
24         4.0    6435       2       0      98       0       0       0
36         2.0   17494       1       0       8       0       0       0
43        12.0       0       2       3      98       0       0       0
...        ...     ...     ...     ...     ...     ...     ...     ...
15373      1.0    8640       1       2      98       0       0       0
15382      7.0    4325       1       0      98       0       0       0
15391      9.0    1861      96       0       2       0       0       0
15412      1.0   11528       1       0      98       0       0       0
15421      8.0    2016       1       0      98       0       0       0

[1474 rows x 88 columns]

In [6]:
df2 = pd.read_excel(r'C:/Users/Federico/Desktop/UdeSA/Maestría/Big Data/TP3/usu_individual_T121.xlsx')
df2.drop(df[df['AGLOMERADO'] < 32.0].index, inplace=True)
df2.drop(df[df['AGLOMERADO'] > 33.0].index, inplace=True)
print(df2)

                              CODUSU  ANO4  TRIMESTRE  NRO_HOGAR  COMPONENTE  \
0      TQRMNOPPQHLKLMCDEFIAH00646702  2021          1          1           1
1      TQRMNOPPRHLKLMCDEFIAH00665104  2021          1          1           1
2      TQRMNOPPRHMOLQCDEFIAH00701809  2021          1          1           1
3      TQRMNOPPRHMOLQCDEFIAH00701809  2021          1          1           2
4      TQRMNOPPRHMOLQCDEFIAH00701809  2021          1          1           3
...                              ...   ...        ...        ...         ...
46688  TQSMNOTRYHLOKPCDEOJAH00652060  2021          1          1           1
46689  TQSMNOTRYHLOKPCDEOJAH00652060  2021          1          1           3
46690  TQSMNOTRYHLOKPCDEOJAH00652060  2021          1          1           4
46691  TQSMNOTRYHLOKPCDEOJAH00652060  2021          1          1           5
46692  TQSMNOTRYHLOKPCDEOJAH00652060  2021          1          1           6

       H15  REGION MAS_500  AGLOMERADO  PONDERA  ...  PDECIFR  ADECIFR  \
0        1      43       S           2      675  ...      0.0      3.0
1        1      43       S           2      675  ...      0.0      2.0
2        1      43       S           2      559  ...      0.0     12.0
3        1      43       S           2      559  ...      0.0     12.0
4        1      43       S           2      559  ...      0.0     12.0
...    ...     ...     ...         ...      ...  ...      ...      ...
46688    1      44       N          93      108  ...      6.0      5.0
46689    1      44       N          93      108  ...      6.0      5.0
46690    0      44       N          93      108  ...      6.0      5.0
46691    0      44       N          93      108  ...      6.0      5.0
46692    0      44       N          93      108  ...      6.0      5.0

          IPCF  DECCFR  IDECCFR  RDECCFR  GDECCFR  PDECCFR  ADECCFR  PONDIH
0      40000.0     8.0      8.0      8.0      8.0      0.0      7.0    1377
1      25000.0     6.0      6.0      6.0      6.0      0.0      5.0     723
2          0.0    12.0     12.0     12.0     12.0      0.0     12.0       0
3          0.0    12.0     12.0     12.0     12.0      0.0     12.0       0
4          0.0    12.0     12.0     12.0     12.0      0.0     12.0       0
...        ...     ...      ...      ...      ...      ...      ...     ...
46688  10800.0     2.0      2.0      2.0      0.0      3.0      1.0      73
46689  10800.0     2.0      2.0      2.0      0.0      3.0      1.0      73
46690  10800.0     2.0      2.0      2.0      0.0      3.0      1.0      73
46691  10800.0     2.0      2.0      2.0      0.0      3.0      1.0      73
46692  10800.0     2.0      2.0      2.0      0.0      3.0      1.0      73

[46693 rows x 177 columns]

In [7]:
import pandas as pd
df3= pd.merge(df, df2, on = "CODUSU", how = "inner")
df3

,CODUSU,ANO4_x,TRIMESTRE_x,NRO_HOGAR_x,REALIZADA,REGION_x,MAS_500_x,AGLOMERADO_x,PONDERA_x,IV1,...,PDECIFR_y,ADECIFR_y,IPCF_y,DECCFR_y,IDECCFR_y,RDECCFR_y,GDECCFR_y,PDECCFR_y,ADECCFR_y,PONDIH_y
0,TQRMNOQXUHJMMUCDEIJAH00693031,2021,1,1,1,1,S,33,3255,1,...,0.0,5.0,13750.00,3.0,0.0,3.0,3.0,0.0,4.0,5286
1,TQRMNOQXUHJMMUCDEIJAH00693031,2021,1,1,1,1,S,33,3255,1,...,0.0,5.0,13750.00,3.0,0.0,3.0,3.0,0.0,4.0,5286
2,TQRMNOQXUHJMMUCDEIJAH00693031,2021,1,1,1,1,S,33,3255,1,...,0.0,5.0,13750.00,3.0,0.0,3.0,3.0,0.0,4.0,5286
3,TQRMNOQXUHJMMUCDEIJAH00693031,2021,1,1,1,1,S,33,3255,1,...,0.0,5.0,13750.00,3.0,0.0,3.0,3.0,0.0,4.0,5286
4,TQRMNOSRPHLLNRCDEIJAH00651171,2021,1,1,1,1,S,33,2331,1,...,0.0,6.0,17500.00,4.0,0.0,4.0,4.0,0.0,5.0,3953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4086,TQRMNOURVHMNONCDEIIAD00700616,2021,1,1,1,1,S,32,3772,2,...,0.0,4.0,58000.00,9.0,0.0,9.0,9.0,0.0,7.0,4325
4087,TQRMNORRWHJMOPCDEIIAD00690119,2021,1,1,1,1,S,32,1379,2,...,0.0,6.0,97500.00,10.0,0.0,10.0,10.0,0.0,9.0,1861
4088,TQRMNOQWRHLOMPCDEIJAH00650932,2021,1,1,1,1,S,33,8638,1,...,0.0,1.0,6333.33,1.0,0.0,1.0,1.0,0.0,1.0,11528
4089,TQRMNOQWRHLOMPCDEIJAH00650932,2021,1,1,1,1,S,33,8638,1,...,0.0,1.0,6333.33,1.0,0.0,1.0,1.0,0.0,1.0,11528
4090,TQRMNOQWRHLOMPCDEIJAH00650932,2021,1,1,1,1,S,33,8638,1,...,0.0,1.0,6333.33,1.0,0.0,1.0,1.0,0.0,1.0,11528

In [12]:
df3.drop(df[df['REGION'] <0].index, inplace=True)
df3.drop(df[df['IPCF'] <0].index, inplace=True)
df3.drop(df[df['PONDIH'] <0].index, inplace=True)
df3.drop(df[df['GDECCFR'] <0].index, inplace=True)
df3.drop(df[df['DECCFR'] <0].index, inplace=True)
df3.drop(df[df['PONDERA'] <0].index, inplace=True)
df3.drop(df[df['IV1'] <0].index, inplace=True)
df3.drop(df[df['PDECIFR'] <0].index, inplace=True)
df3.drop(df[df['ADECIFR'] <0].index, inplace=True)
df3.drop(df[df['ADECCFR'] <0].index, inplace=True)
df3

,CODUSU,ANO4_x,TRIMESTRE_x,NRO_HOGAR_x,REALIZADA,REGION_x,MAS_500_x,AGLOMERADO_x,PONDERA_x,IV1,...,PDECIFR_y,ADECIFR_y,IPCF_y,DECCFR_y,IDECCFR_y,RDECCFR_y,GDECCFR_y,PDECCFR_y,ADECCFR_y,PONDIH_y
0,TQRMNOQXUHJMMUCDEIJAH00693031,2021,1,1,1,1,S,33,3255,1,...,0.0,5.0,13750.00,3.0,0.0,3.0,3.0,0.0,4.0,5286
1,TQRMNOQXUHJMMUCDEIJAH00693031,2021,1,1,1,1,S,33,3255,1,...,0.0,5.0,13750.00,3.0,0.0,3.0,3.0,0.0,4.0,5286
2,TQRMNOQXUHJMMUCDEIJAH00693031,2021,1,1,1,1,S,33,3255,1,...,0.0,5.0,13750.00,3.0,0.0,3.0,3.0,0.0,4.0,5286
3,TQRMNOQXUHJMMUCDEIJAH00693031,2021,1,1,1,1,S,33,3255,1,...,0.0,5.0,13750.00,3.0,0.0,3.0,3.0,0.0,4.0,5286
4,TQRMNOSRPHLLNRCDEIJAH00651171,2021,1,1,1,1,S,33,2331,1,...,0.0,6.0,17500.00,4.0,0.0,4.0,4.0,0.0,5.0,3953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4086,TQRMNOURVHMNONCDEIIAD00700616,2021,1,1,1,1,S,32,3772,2,...,0.0,4.0,58000.00,9.0,0.0,9.0,9.0,0.0,7.0,4325
4087,TQRMNORRWHJMOPCDEIIAD00690119,2021,1,1,1,1,S,32,1379,2,...,0.0,6.0,97500.00,10.0,0.0,10.0,10.0,0.0,9.0,1861
4088,TQRMNOQWRHLOMPCDEIJAH00650932,2021,1,1,1,1,S,33,8638,1,...,0.0,1.0,6333.33,1.0,0.0,1.0,1.0,0.0,1.0,11528
4089,TQRMNOQWRHLOMPCDEIJAH00650932,2021,1,1,1,1,S,33,8638,1,...,0.0,1.0,6333.33,1.0,0.0,1.0,1.0,0.0,1.0,11528
4090,TQRMNOQWRHLOMPCDEIJAH00650932,2021,1,1,1,1,S,33,8638,1,...,0.0,1.0,6333.33,1.0,0.0,1.0,1.0,0.0,1.0,11528

In [24]:
dfss = df3[['IV1','IV6','IV8','V5','ITF_y','IPCF_y']].copy()
dfss.describe(include='all')

,IV1,IV6,IV8,V5,ITF_y,IPCF_y
count,4091.000000,4091.00000,4091.000000,4091.000000,4091.000000,4091.000000
mean,1.311171,1.01320,1.001711,1.854070,54525.938890,18794.249553
std,0.489219,0.11835,0.041335,0.609196,77080.708389,28333.916280
min,1.000000,1.00000,1.000000,1.000000,0.000000,0.000000
25%,1.000000,1.00000,1.000000,2.000000,0.000000,0.000000
50%,1.000000,1.00000,1.000000,2.000000,32200.000000,10000.000000
75%,2.000000,1.00000,1.000000,2.000000,77000.000000,26250.000000
max,4.000000,3.00000,2.000000,9.000000,750000.000000,307500.000000

In [25]:
def evalua_metodo (modelo, x_train, y_train, x_test, y_test):
    '''
    Esta función parte de un modelo predictivo definido previamente y luego evalúa sus principales métricas
    resultantes
    Imput:
          Modelo, x_train, y_train, x_test, y_test
    output:
          Matriz de confusión,AUC, ROC, ACCURACY SCORE
    '''
    accuracy_modelo = accuracy_score(y_test, y_pred_modelo)
    matriz_confusion = confusion_matrix(y_test, y_pred_modelo)
    auc = roc_auc_score(y_test, y_pred_modelo)
    return (accuracy_modelo, matriz_confusion, auc)